export const pokemons = [
    {
        id: 1,
        name: "Bulbasaur",
        type: "Grass",
        base_experience: 64,
    },
    {
        id: 2,
        name: "Ivysaur",
        type: "Grass",
        base_experience: 142,
    },
    {
        id: 3,
        name: "Venusaur",
        type: "Grass",
        base_experience: 236,
    },
    {
        id: 4,
        name: "Charmander",
        type: "Fire",
        base_experience: 62,
    },
    {
        id: 5,
        name: "Charmeleon",
        type: "Fire",
        base_experience: 142,
    },
    {
        id: 6,
        name: "Charizard",
        type: "Fire",
        base_experience: 240,
    },
    {
        id: 7,
        name: "Squirtle",
        type: "Water",
        base_experience: 63,
    },
    {
        id: 8,
        name: "Wartortle",
        type: "Water",
        base_experience: 142,
    },
    {
        id: 9,
        name: "Blastoise",
        type: "Water",
        base_experience: 239,
    },
    {
        id: 10,
        name: "Caterpie",
        type: "Bug",
        base_experience: 39,
    },
    {
        id: 11,
        name: "Metapod",
        type: "Bug",
        base_experience: 72,
    },
    {
        id: 12,
        name: "Butterfree",
        type: "Bug",
        base_experience: 178,
    },
    {
        id: 13,
        name: "Weedle",
        type: "Bug",
        base_experience: 39,
    },
    {
        id: 14,
        name: "Kakuna",
        type: "Bug",
        base_experience: 72,
    },
    {
        id: 15,
        name: "Beedrill",
        type: "Bug",
        base_experience: 178,
    },
    {
        id: 16,
        name: "Pidgey",
        type: "Normal",
        base_experience: 50,
    },
    {
        id: 17,
        name: "Pidgeotto",
        type: "Normal",
        base_experience: 122,
    },
    {
        id: 18,
        name: "Pidgeot",
        type: "Normal",
        base_experience: 216,
    },
    {
        id: 19,
        name: "Rattata",
        type: "Normal",
        base_experience: 51,
    },
    {
        id: 20,
        name: "Raticate",
        type: "Normal",
        base_experience: 145,
    },
    {
        id: 21,
        name: "Spearow",
        type: "Normal",
        base_experience: 52,
    },
    {
        id: 22,
        name: "Fearow",
        type: "Normal",
        base_experience: 155,
    },
    {
        id: 23,
        name: "Ekans",
        type: "Poison",
        base_experience: 58,
    },
    {
        id: 24,
        name: "Arbok",
        type: "Poison",
        base_experience: 153,
    },
    {
        id: 25,
        name: "Pikachu",
        type: "Electric",
        base_experience: 112,
    },
    {
        id: 26,
        name: "Raichu",
        type: "Electric",
        base_experience: 218,
    },
    {
        id: 27,
        name: "Sandshrew",
        type: "Ground",
        base_experience: 60,
    },
    {
        id: 28,
        name: "Sandslash",
        type: "Ground",
        base_experience: 158,
    },
    {
        id: 29,
        name: "Nidoran",
        type: "Poison",
        base_experience: 55,
    },
    {
        id: 30,
        name: "Nidorina",
        type: "Poison",
        base_experience: 128,
    },
    {
        id: 31,
        name: "Nidoqueen",
        type: "Poison",
        base_experience: 227,
    },
    {
        id: 32,
        name: "Nidoran",
        type: "Poison",
        base_experience: 55,
    },
    {
        id: 33,
        name: "Nidorino",
        type: "Poison",
        base_experience: 128,
    },
    {
        id: 34,
        name: "Nidoking",
        type: "Poison",
        base_experience: 227,
    },
    {
        id: 35,
        name: "Clefairy",
        type: "Fairy",
        base_experience: 113,
    },
    {
        id: 36,
        name: "Clefable",
        type: "Fairy",
        base_experience: 217,
    },
    {
        id: 37,
        name: "Vulpix",
        type: "Fire",
        base_experience: 60,
    },
    {
        id: 38,
        name: "Ninetales",
        type: "Fire",
        base_experience: 177,
    },
    {
        id: 39,
        name: "Jigglypuff",
        type: "Normal",
        base_experience: 95,
    },
    {
        id: 40,
        name: "Wigglytuff",
        type: "Normal",
        base_experience: 196,
    },
    {
        id: 41,
        name: "Zubat",
        type: "Poison",
        base_experience: 49,
    },
    {
        id: 42,
        name: "Golbat",
        type: "Poison",
        base_experience: 159,
    },
    {
        id: 43,
        name: "Oddish",
        type: "Grass",
        base_experience: 64,
    },
    {
        id: 44,
        name: "Gloom",
        type: "Grass",
        base_experience: 138,
    },
    {
        id: 45,
        name: "Vileplume",
        type: "Grass",
        base_experience: 221,
    },
    {
        id: 46,
        name: "Paras",
        type: "Bug",
        base_experience: 57,
    },
    {
        id: 47,
        name: "Parasect",
        type: "Bug",
        base_experience: 142,
    },
    {
        id: 48,
        name: "Venonat",
        type: "Bug",
        base_experience: 61,
    },
    {
        id: 49,
        name: "Venomoth",
        type: "Bug",
        base_experience: 158,
    },
    {
        id: 50,
        name: "Diglett",
        type: "Ground",
        base_experience: 53,
    },
    {
        id: 51,
        name: "Dugtrio",
        type: "Ground",
        base_experience: 149,
    },
    {
        id: 52,
        name: "Meowth",
        type: "Normal",
        base_experience: 58,
    },
    {
        id: 53,
        name: "Persian",
        type: "Normal",
        base_experience: 154,
    },
    {
        id: 54,
        name: "Psyduck",
        type: "Water",
        base_experience: 64,
    },
    {
        id: 55,
        name: "Golduck",
        type: "Water",
        base_experience: 175,
    },
    {
        id: 56,
        name: "Mankey",
        type: "Fighting",
        base_experience: 61,
    },
    {
        id: 57,
        name: "Primeape",
        type: "Fighting",
        base_experience: 159,
    },
    {
        id: 58,
        name: "Growlithe",
        type: "Fire",
        base_experience: 70,
    },
    {
        id: 59,
        name: "Arcanine",
        type: "Fire",
        base_experience: 194,
    },
    {
        id: 60,
        name: "Poliwag",
        type: "Water",
        base_experience: 60,
    },
    {
        id: 61,
        name: "Poliwhirl",
        type: "Water",
        base_experience: 135,
    },
    {
        id: 62,
        name: "Poliwrath",
        type: "Water",
        base_experience: 230,
    },
    {
        id: 63,
        name: "Abra",
        type: "Psychic",
        base_experience: 62,
    },
    {
        id: 64,
        name: "Kadabra",
        type: "Psychic",
        base_experience: 140,
    }
];

export const quotes = [
    {
        id: 1,
        quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    },
    {
        id: 2,
        quote: "The way to get started is to quit talking and begin doing.",
    },
    {
        id: 3,
        quote: "Your time is limited, so don't waste it living someone else's life.",
    },
    {
        id: 4,
        quote: "If life were predictable it would cease to be life, and be without flavor.",
    },
    {
        id: 5,
        quote: "If you look at what you have in life, you'll always have more.",
    },
    {
        id: 6,
        quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
    },
    {
        id: 7,
        quote: "Life is what happens when you're busy making other plans.",
    },
    {
        id: 8,
        quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    },
    {
        id: 9,
        quote: "When you reach the end of your rope, tie a knot in it and hang on.",
    },
    {
        id: 10,
        quote: "Always remember that you are absolutely unique. Just like everyone else.",
    },
    {
        id: 11,
        quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    },
    {
        id: 12,
        quote: "The future belongs to those who believe in the beauty of their dreams.",
    },
    {
        id: 13,
        quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    },
    {
        id: 14,
        quote: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    },
    {
        id: 15,
        quote: "It is during our darkest moments that we must focus to see the light.",
    },
    {
        id: 16,
        quote: "Whoever is happy will make others happy too.",
    },
    {
        id: 17,
        quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    },
    {
        id: 18,
        quote:"The only impossible journey is the one you never begin.",
    },
    {
        id: 19,
        quote: "You are never too old to set another goal or to dream a new dream.",
    },
    {
        id: 20,
        quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    },
    {
        id: 21,
        quote: "It is our choices, that show what we truly are, far more than our abilities.",
    },
    {
        id: 22,
        quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    },
    {
        id: 23,
        quote: "The way to get started is to quit talking and begin doing.",
    },
    {
        id: 24,
        quote: "Your time is limited, so don't waste it living someone else's life.",
    },
    {
        id: 25,
        quote: "If life were predictable it would cease to be life, and be without flavor.",
    },
    {
        id: 26,
        quote: "If you look at what you have in life, you'll always have more.",
    },
    {
        id: 27,
        quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
    },
    {
        id: 28,
        quote: "Life is what happens when you're busy making other plans.",
    },
    {
        id: 29,
        quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    },
    {
        id: 30,
        quote: "When you reach the end of your rope, tie a knot in it and hang on.",
    },
    {
        id: 31,
        quote: "Always remember that you are absolutely unique. Just like everyone else.",
    },
    {
        id: 32,
        quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    },
    {
        id: 33,
        quote: "The future belongs to those who believe in the beauty of their dreams.",
    },
    {
        id: 34,
        quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    },
    {
        id: 35,
        quote: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    },
    {
        id: 36,
        quote: "It is during our darkest moments that we must focus to see the light.",
    },
    {
        id: 37,
        quote: "Whoever is happy will make others happy too.",
    },
    {
        id: 38,
        quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    },
    {
        id: 39,
        quote: "The only impossible journey is the one you never begin.",
    },
    {
        id: 40,
        quote: "You are never too old to set another goal or to dream a new dream.",
    },
    {
        id: 41,
        quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    },
    {
        id: 42,
        quote: "It is our choices, that show what we truly are, far more than our abilities.",
    },
    {
        id: 43,
        quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    },
    {
        id: 44,
        quote: "The way to get started is to quit talking and begin doing.",
    },
    {
        id: 45,
        quote: "Your time is limited, so don't waste it living someone else's life.",
    },
    {
        id: 46,
        quote: "If life were predictable it would cease to be life, and be without flavor.",
    },
    {
        id: 47,
        quote: "If you look at what you have in life, you'll always have more.",
    },
    {
        id: 48,
        quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
    },
    {
        id: 49,
        quote: "Life is what happens when you're busy making other plans.",
    },
    {
        id: 50,
        quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    }
];

export const users = [
    {
        id: 1,
        name: "Leanne Graham",
        username: "Bret",
        created_at: "2021-01-01T00:00:00.000Z",
    },
    {
        id: 2,
        name: "Ervin Howell",
        username: "Antonette",
        created_at: "2021-01-02T00:00:00.000Z",
    },
    {
        id: 3,
        name: "Clementine Bauch",
        username: "Samantha",
        created_at: "2021-01-03T00:00:00.000Z",
    },
    {
        id: 4,
        name: "Patricia Lebsack",
        username: "Karianne",
        created_at: "2021-01-04T00:00:00.000Z",
    },
    {
        id: 5,
        name: "Chelsey Dietrich",
        username: "Kamren",
        created_at: "2021-01-05T00:00:00.000Z",
    },
    {
        id: 6,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        created_at: "2021-01-06T00:00:00.000Z",
    },
    {
        id: 7,
        name: "Kurtis Weissnat",
        username: "Elwyn.Skiles",
        created_at: "2021-01-07T00:00:00.000Z",
    },
    {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        created_at: "2021-01-08T00:00:00.000Z",
    },
    {
        id: 9,
        name: "Glenna Reichert",
        username: "Delphine",
        created_at: "2021-01-09T00:00:00.000Z",
    },
    {
        id: 10,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        created_at: "2021-01-10T00:00:00.000Z",
    },
    {
        id: 11,
        name: "Leanne Graham",
        username: "Bret",
        created_at: "2021-01-11T00:00:00.000Z",
    },
    {
        id: 12,
        name: "Ervin Howell",
        username: "Antonette",
        created_at: "2021-01-12T00:00:00.000Z",
    },
    {
        id: 13,
        name: "Clementine Bauch",
        username: "Samantha",
        created_at: "2021-01-13T00:00:00.000Z",
    },
    {
        id: 14,
        name: "Patricia Lebsack",
        username: "Karianne",
        created_at: "2021-01-14T00:00:00.000Z",
    },
    {
        id: 15,
        name: "Chelsey Dietrich",
        username: "Kamren",
        created_at: "2021-01-15T00:00:00.000Z",
    },
    {
        id: 16,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        created_at: "2021-01-16T00:00:00.000Z",
    },
    {
        id: 17,
        name: "Kurtis Weissnat",
        username: "Elwyn.Skiles",
        created_at: "2021-01-17T00:00:00.000Z",
    },
    {
        id: 18,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        created_at: "2021-01-18T00:00:00.000Z",
    },
    {
        id: 19,
        name: "Glenna Reichert",
        username: "Delphine",
        created_at: "2021-01-19T00:00:00.000Z",
    },
    {
        id: 20,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        created_at: "2021-01-20T00:00:00.000Z",
    },
    {
        id: 21,
        name: "Leanne Graham",
        username: "Bret",
        created_at: "2021-01-21T00:00:00.000Z",
    },
    {
        id: 22,
        name: "Ervin Howell",
        username: "Antonette",
        created_at: "2021-01-22T00:00:00.000Z",
    },
    {
        id: 23,
        name: "Clementine Bauch",
        username: "Samantha",
        created_at: "2021-01-23T00:00:00.000Z",
    },
    {
        id: 24,
        name: "Patricia Lebsack",
        username: "Karianne",
        created_at: "2021-01-24T00:00:00.000Z",
    },
    {
        id: 25,
        name: "Chelsey Dietrich",
        username: "Kamren",
        created_at: "2021-01-25T00:00:00.000Z",
    },
    {
        id: 26,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        created_at: "2021-01-26T00:00:00.000Z",
    },
    {
        id: 27,
        name: "Kurtis Weissnat",
        username: "Elwyn.Skiles",
        created_at: "2021-01-27T00:00:00.000Z",
    },
    {
        id: 28,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        created_at: "2021-01-28T00:00:00.000Z",
    },
    {
        id: 29,
        name: "Glenna Reichert",
        username: "Delphine",
        created_at: "2021-01-29T00:00:00.000Z",
    },
    {
        id: 30,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        created_at: "2021-01-30T00:00:00.000Z",
    },
    {
        id: 31,
        name: "Leanne Graham",
        username: "Bret",
        created_at: "2021-01-31T00:00:00.000Z",
    },
    {
        id: 32,
        name: "Ervin Howell",
        username: "Antonette",
        created_at: "2021-02-01T00:00:00.000Z",
    },
    {
        id: 33,
        name: "Clementine Bauch",
        username: "Samantha",
        created_at: "2021-02-02T00:00:00.000Z",
    },
    {
        id: 34,
        name: "Patricia Lebsack",
        username: "Karianne",
        created_at: "2021-02-03T00:00:00.000Z",
    },
    {
        id: 35,
        name: "Chelsey Dietrich",
        username: "Kamren",
        created_at: "2021-02-04T00:00:00.000Z",
    },
    {
        id: 36,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        created_at: "2021-02-05T00:00:00.000Z",
    },
    {
        id: 37,
        name: "Kurtis Weissnat",
        username: "Elwyn.Skiles",
        created_at: "2021-02-06T00:00:00.000Z",
    },
    {
        id: 38,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        created_at: "2021-02-07T00:00:00.000Z",
    },
    {
        id: 39,
        name: "Glenna Reichert",
        username: "Delphine",
        created_at: "2021-02-08T00:00:00.000Z",
    },
    {
        id: 40,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        created_at: "2021-02-09T00:00:00.000Z",
    },
    {
        id: 41,
        name: "Leanne Graham",
        username: "Bret",
        created_at: "2021-02-10T00:00:00.000Z",
    },
    {
        id: 42,
        name: "Ervin Howell",
        username: "Antonette",
        created_at: "2021-02-11T00:00:00.000Z",
    },
    {
        id: 43,
        name: "Clementine Bauch",
        username: "Samantha",
        created_at: "2021-02-12T00:00:00.000Z",
    },
    {
        id: 44,
        name: "Patricia Lebsack",
        username: "Karianne",
        created_at: "2021-02-13T00:00:00.000Z",
    },
    {
        id: 45,
        name: "Chelsey Dietrich",
        username: "Kamren",
        created_at: "2021-02-14T00:00:00.000Z",
    },
    {
        id: 46,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        created_at: "2021-02-15T00:00:00.000Z",
    },
    {
        id: 47,
        name: "Kurtis Weissnat",
        username: "Elwyn.Skiles",
        created_at: "2021-02-16T00:00:00.000Z",
    },
    {
        id: 48,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        created_at: "2021-02-17T00:00:00.000Z",
    },
    {
        id: 49,
        name: "Glenna Reichert",
        username: "Delphine",
        created_at: "2021-02-18T00:00:00.000Z",
    },
    {
        id: 50,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        created_at: "2021-02-19T00:00:00.000Z",
    }
];